name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Test
      run: |
        cd src
        dotnet test --no-restore --verbosity normal
